
reference:
  path: '/media/b085164/Elements/PCD_SAM/Georef_v6/ref/merged/merged_94117_HA_LR.txt'

targets:
  - path: '/media/b085164/Elements/PCD_SAM/Georef_v6_full/scan2scan/merged/merged_94117_HA_LR.txt'
    outfile: '/media/b085164/Elements/PCD_SAM/Georef_v6_full/georef_errors/rmse_ref_w_scan2scan.las'

  - path: '/media/b085164/Elements/PCD_SAM/Georef_v6_full/chunk2chunk/merged/merged_94117_HA_LR.txt'
    outfile: '/media/b085164/Elements/PCD_SAM/Georef_v6_full/georef_errors/rmse_ref_w_chunk2chunk.las'


time:
  outage_start: 466930.0
  outage_duration: 200.0
  buffer: 0.0

io:
  delim: ","
  no_header: true  

matching:
  exact_time: true # match on exact GPS times
  time_atol: 0.0    # ignored if exact_time=true

las:
  scale: 0.001      # 1 mm precision