
reference:
  path: '/media/b085164/Elements/PCD_SAM/Georef_v6/ref/merged/merged_94117_HA_LR.txt'

targets:
  - path: '/media/b085164/Elements/PCD_SAM/Georef_v6/outage_only/merged/merged_94117_HA_LR.txt'
    outfile: '/media/b085164/Elements/PCD_SAM/Georef_v6/georef_errors/rmse_ref_w_outage_only.las'

  - path: '/media/b085164/Elements/PCD_SAM/Georef_v6/limatch_scan2scan/merged/merged_94117_HA_LR.txt'
    outfile: '/media/b085164/Elements/PCD_SAM/Georef_v6/georef_errors/rmse_ref_w_p2p_scan2scan.las'

  - path: '/media/b085164/Elements/PCD_SAM/Georef_v6/limatch_chunk2chunk/merged/merged_94117_HA_LR.txt'
    outfile: '/media/b085164/Elements/PCD_SAM/Georef_v6/georef_errors/rmse_ref_w_p2p_chunk2chunk.las'
time:
  outage_start: 466930.0
  outage_duration: 200.0
  buffer: 0.0

io:
  delim: ","
  no_header: true   # assumes columns: gps_time,x,y,z,...

matching:
  # only used to validate times if you want allclose instead of exact equal
  exact_time: true
  time_atol: 0.0    # ignored if exact_time=true

las:
  scale: 0.001      # 1 mm precision