project_root: /media/b085164/Elements/PCD_SAM/Georef_test
repo_root: /home/b085164/PDM_Romain_Defferrard/ESO-PDM
python_exec: python3
scenario:
  method: ref
  run_name: ''
  mode: GeorefOnly
  manual_scenario_root: false
paths:
  traj_path: /media/b085164/Elements/Gobet_ODyN_v1/v1_base_AB/out/reference.out
  sdc_ha: /media/b085164/Elements/RD_SAM_SDC/subset_HA
  sdc_lr: /media/b085164/Elements/RD_SAM_SDC/subset_LR
  gps_in: /media/b085164/Elements/Gobet_ODyN_v1/v1_base_AB/in/GPS.txt
  patcher_cfg_template: /home/b085164/PDM_Romain_Defferrard/ESO-PDM/Patcher/config/MLS_Epalinges_config.yml
  limatch_cfg_template: /home/b085164/PDM_Romain_Defferrard/ESO-PDM/Patcher/submodules/limatch/configs/MLS.yml
  patcher_out_root: /media/b085164/Elements/PCD_SAM/parking/output_Patcher
outputs:
  scenario_root: /media/b085164/Elements/PCD_SAM/Georef_test/ref
  merged_dirname: merged
  tmp_dirname: tmp
  limatch_dirname: output_limatch
  chunks_dirname: chunks
  patcher_dirname: output_patcher
  results_dirname: results
  logs_dirname: logs
execution:
  do_georef_merge: true
  delete_tmp_after_success: true
  do_chunks: true
  reuse_chunks: true
  force_rebuild_chunks: false
  do_gps_outage: false
  show_intermediate_outputs: false
merge:
  delimiter: ','
  skiprows: 0
  sort_by_time: true
  out_prefix: merged_
  out_suffix: _HA_LR
chunk:
  length_m: 15.0
  min_points: 2000
  neighbor_k: 1
  do_cross_scan: true
  epsg_out: EPSG:2056
outage:
  start: 466930.0
  duration: 200.0
  pre: 30.0
  post: 30.0
  outages:
  - - 466930.0
    - 200.0
cycleslip:
  scenarios:
  - name: slip_default
    slips:
    - t0: 466930.0
      duration: 60.0
      dx: 1.0
      dy: 0.0
      dz: 0.0
      shape: step
